/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : FLASH.c
**     Project     : SeismicPi_Firmware
**     Processor   : MK22FN128VLH10
**     Component   : IntFLASH
**     Version     : Component 02.409, Driver 01.02, CPU db: 3.00.000
**     Repository  : Kinetis
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-09-04, 09:33, # CodeGen: 0
**     Abstract    :
**         This component "IntFLASH" implements an access to internal FLASH.
**         The component support reading/writing data into FLASH, erasing of
**         selected sector.
**         The component supports events if the write interrupt is supported.
**         The component supports following modes of write operations:
**           - Write - writing without any test.
**           - Destructive write - sector is erased if necessary.
**           - Safe write - user event is invoked to save and resore data
**                          from the current sector.
**         The component requires on-chip FLASH memory (not used/allocated by
**         other components).
**     Settings    :
**          Component name                                 : FLASH
**          FLASH                                          : FTFA
**          FLASH_LDD                                      : FLASH_LDD
**          Write method                                   : Safe write (with save & erase)
**            Buffer type                                  : Implemented by the component
**          Interrupt service/event                        : Disabled
**          Wait in RAM                                    : yes
**          Virtual page                                   : Disabled
**          Initialization                                 : 
**            Events enabled in init.                      : yes
**            Wait enabled in init.                        : yes
**          CPU clock/speed selection                      : 
**            FLASH clock                                  : 
**            High speed mode                              : This component enabled
**            Low speed mode                               : This component enabled
**            Slow speed mode                              : This component disabled
**     Contents    :
**         DisableEvent  - byte FLASH_DisableEvent(void);
**         EnableEvent   - byte FLASH_EnableEvent(void);
**         SetBlockFlash - byte FLASH_SetBlockFlash(FLASH_TDataAddress Source, FLASH_TAddress Dest, word...
**         GetBlockFlash - byte FLASH_GetBlockFlash(FLASH_TAddress Source, FLASH_TDataAddress Dest, word...
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file FLASH.c
** @version 01.02
** @brief
**         This component "IntFLASH" implements an access to internal FLASH.
**         The component support reading/writing data into FLASH, erasing of
**         selected sector.
**         The component supports events if the write interrupt is supported.
**         The component supports following modes of write operations:
**           - Write - writing without any test.
**           - Destructive write - sector is erased if necessary.
**           - Safe write - user event is invoked to save and resore data
**                          from the current sector.
**         The component requires on-chip FLASH memory (not used/allocated by
**         other components).
*/         
/*!
**  @addtogroup FLASH_module FLASH module documentation
**  @{
*/         

/* MODULE FLASH. */

#include "FLASH.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Internal method prototypes */

#define FLASH_TOTAL_FLASH_BLOCK_COUNT  0x01U
#define FLASH_P_FLASH_SIZE             0x00020000U
#define FLASH_P_FLASH_BLOCK_COUNT      0x01U
#define FLASH_P_FLASH_BLOCK_SIZE       0x00020000U

#define FLASH_CMD_NONE                 0x00U
#define FLASH_CMD_READ                 0x01U
#define FLASH_CMD_ERASE_SECTOR         0x02U
#define FLASH_CMD_ERASE_BLOCK          0x03U
#define FLASH_CMD_VERIFY_ERASED_BLOCK  0x04U
#define FLASH_CMD_WRITE                0x05U
#define FLASH_CMD_WRITE_ERASE          0x06U

typedef struct FLASH_TSector_Struct {
  uint32_t Data[IntFlashLdd1_ERASABLE_UNIT_SIZE/4U];
} FLASH_TSector;

static uint32_t FLASH_CurrentCommand;  /* Current command */
static bool FLASH_CmdResult;           /* Last command result */
static bool FLASH_CmdPending;          /* Current command state */
static bool FLASH_EnEvent;             /* State of events (enabled/disabled) */

static LDD_TDeviceData* IntFlashLdd1_DevDataPtr;
static LDD_TData *FLASH_CurrentDataAddress;
static LDD_FLASH_TDataSize FLASH_CurrentDataSize;
static LDD_FLASH_TAddress FLASH_FlashAddress;
static LDD_TData *FLASH_NextSrcDataAddress;
static LDD_FLASH_TDataSize FLASH_RemainingDataSize;
static FLASH_TSector tmpSector;

byte FLASH_SetFlash(FLASH_TDataAddress Source, FLASH_TAddress Dest, word Count);

/*
** ===================================================================
**     Method      :  FLASH_SetFlash (component IntFLASH)
**
**     Description :
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
byte FLASH_SetFlash(FLASH_TDataAddress Src, FLASH_TAddress Dst, word Count)
{
  LDD_TError                 Result;
  uint32_t                   x;
  uint32_t                   SectorAddress, SectorOffset;

  if (FLASH_CmdPending) {
    return ERR_BUSY;
  }
  Result = ERR_OK;                     /* Suppose area is erased */
  for (x=0U; x<Count; x++) {           /* Check if written area is erased */
    if (((uint8_t*)Dst)[x] != 0xFFU) { /* Byte erased? */
      Result = ERR_FAILED;             /* No, Erase is required */
     break;
    }
  }
  if (Result == ERR_FAILED) {
    SectorAddress = Dst & ~(LDD_FLASH_TAddress)IntFlashLdd1_ERASABLE_UNIT_MASK;
    SectorOffset = Dst & IntFlashLdd1_ERASABLE_UNIT_MASK;
    tmpSector = *(FLASH_TSector *)SectorAddress; /* Create copy of the sector */
    do {                               /* Rewrite part of the sector with new data */
      ((uint8_t*)(void*)&tmpSector)[SectorOffset] = *(uint8_t*)(void*)(Src);
      Src++;
      Count--;
    } while ((++SectorOffset != IntFlashLdd1_ERASABLE_UNIT_SIZE) && (Count != 0U));
    FLASH_CmdPending = TRUE;
    FLASH_CurrentCommand = FLASH_CMD_WRITE_ERASE;
    FLASH_CurrentDataAddress = (LDD_TData *)&tmpSector;
    FLASH_CurrentDataSize = IntFlashLdd1_ERASABLE_UNIT_SIZE;
    FLASH_FlashAddress = SectorAddress;
    FLASH_NextSrcDataAddress = (LDD_TData *)Src;
    FLASH_RemainingDataSize = (LDD_FLASH_TDataSize) Count;
    Result = IntFlashLdd1_Erase(IntFlashLdd1_DevDataPtr, FLASH_FlashAddress, FLASH_CurrentDataSize);
    if (Result == ERR_OK) {
      do {
        IntFlashLdd1_Main(IntFlashLdd1_DevDataPtr);
      } while (FLASH_CmdPending);
      Result = FLASH_CmdResult;
    } else {
      FLASH_CmdPending = FALSE;        /* Command parameter error */
      if (Result == ERR_PARAM_ADDRESS) {
        Result = ERR_RANGE;
      }
    }
    return (byte)Result;
  }
  FLASH_RemainingDataSize = 0U;
  FLASH_CurrentCommand = FLASH_CMD_WRITE;
  FLASH_CmdPending = TRUE;
  Result = IntFlashLdd1_Write(IntFlashLdd1_DevDataPtr, (LDD_TData *)Src, Dst, (LDD_FLASH_TDataSize)Count); /* Start reading from the flash memory */
  if (Result == ERR_OK) {
    do {
      IntFlashLdd1_Main(IntFlashLdd1_DevDataPtr);
    } while (FLASH_CmdPending);
    Result = FLASH_CmdResult;
  } else {
    FLASH_CmdPending = FALSE;          /* Command parameter error */
    if (Result == ERR_PARAM_ADDRESS) {
      Result = ERR_RANGE;
    }
  }
  return (byte)Result;
}

/*
** ===================================================================
**     Method      :  FLASH_Init (component IntFLASH)
**
**     Description :
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void FLASH_Init(void)
{
  IntFlashLdd1_DevDataPtr = IntFlashLdd1_Init(NULL);
  FLASH_CmdPending = FALSE;
  FLASH_EnEvent = TRUE;                /* Remember events state */
}

/*
** ===================================================================
**     Method      :  FLASH_DisableEvent (component IntFLASH)
*/
/*!
**     @brief
**         This method disables all the events except [OnSaveBuffer],
**         [OnRestoreBuffer] and [OnEraseError]. The method is
**         available only if any event is enabled.
**     @return
**                         - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_SPEED - This device does not work in
**                           the active speed mode
*/
/* ===================================================================*/
byte FLASH_DisableEvent(void)
{
  FLASH_EnEvent = FALSE;
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  FLASH_EnableEvent (component IntFLASH)
*/
/*!
**     @brief
**         This method enables all the events except [OnSaveBuffer],
**         [OnRestoreBuffer] and [OnEraseError]. The method is
**         available only if any event is enabled.
**     @return
**                         - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_SPEED - This device does not work in
**                           the active speed mode
*/
/* ===================================================================*/
byte FLASH_EnableEvent(void)
{
  FLASH_EnEvent = TRUE;
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  FLASH_SetBlockFlash (component IntFLASH)
*/
/*!
**     @brief
**         Writes data to FLASH. The operation of this method depends
**         on the "Write method" property and state of the flash.
**         Please see more details on general info page of the help.
**     @param
**         Source          - Source address of the data.
**     @param
**         Dest            - Destination address in FLASH.
**     @param
**         Count           - Count of the data fields (in the
**                           smallest addressable units).
**     @return
**                         - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_NOTAVAIL - Desired program/erase
**                           operation is not available 
**                           - ERR_RANGE - The address is out of range 
**                           - ERR_BUSY - Device is busy 
**                           - ERR_SPEED - This device does not work in
**                           the active speed mode 
**                           - ERR_PROTECT - Flash is write protect 
**                           - ERR_VALUE - Read value is not equal to
**                           written value
*/
/* ===================================================================*/
byte FLASH_SetBlockFlash(FLASH_TDataAddress Source, FLASH_TAddress Dest, word Count)
{
  return FLASH_SetFlash(Source, Dest, Count);
}

/*
** ===================================================================
**     Method      :  FLASH_GetBlockFlash (component IntFLASH)
*/
/*!
**     @brief
**         Reads data from FLASH.
**     @param
**         Source          - Destination address in FLASH.
**     @param
**         Dest            - Source address of the data.
**     @param
**         Count           - Count of the data fields (in the
**                           smallest addressable units).
**     @return
**                         - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_NOTAVAIL - Desired program/erase
**                           operation is not available 
**                           - ERR_RANGE - The address is out of range 
**                           - ERR_BUSY - Device is busy
*/
/* ===================================================================*/
byte FLASH_GetBlockFlash(FLASH_TAddress Source, FLASH_TDataAddress Dest, word Count)
{
  LDD_TError                 Result;
  
  if (FLASH_CmdPending) {
    return ERR_BUSY;
  }
  FLASH_CurrentCommand = FLASH_CMD_READ;
  FLASH_CmdPending = TRUE;
  Result = IntFlashLdd1_Read(IntFlashLdd1_DevDataPtr, (LDD_FLASH_TAddress)Source, (LDD_TData*)Dest, (LDD_FLASH_TDataSize)Count); /* Start reading from the flash memory */
  if (Result == ERR_OK) {              /* Command accepted? */
    do {
      IntFlashLdd1_Main(IntFlashLdd1_DevDataPtr);
    } while (FLASH_CmdPending);
    Result = FLASH_CmdResult;
  } else if (Result == ERR_PARAM_ADDRESS) {
    FLASH_CmdPending = FALSE;
    Result = ERR_RANGE;
  } else {
  }
  return (byte)Result;
}

/*
** ===================================================================
**     Method      :  FLASH_OnOperationComplete (component IntFLASH)
**
**     Description :
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void IntFlashLdd1_OnOperationComplete(LDD_TUserData *UserDataPtr)
{
  uint32_t  x;
  
  (void)UserDataPtr;                   /* Parameter is not used, suppress unused argument warning */
  FLASH_CmdResult = ERR_OK;            /* No error appears */
  switch (FLASH_CurrentCommand) {
    case FLASH_CMD_WRITE:
      if (FLASH_RemainingDataSize != 0U) {
        FLASH_CurrentDataAddress = FLASH_NextSrcDataAddress;
        FLASH_FlashAddress += FLASH_CurrentDataSize;
        if (FLASH_RemainingDataSize % IntFlashLdd1_ERASABLE_UNIT_SIZE) {
          /* Remaining data size is NOT multiple of sector size */
          if (FLASH_RemainingDataSize < IntFlashLdd1_ERASABLE_UNIT_SIZE) { /* Last sector? */
            for (x=0U; x<IntFlashLdd1_ERASABLE_UNIT_SIZE;x++) {
              if (x<FLASH_RemainingDataSize) {
                ((uint8_t*)(void*)&tmpSector)[x] = ((uint8_t*)(void*)FLASH_NextSrcDataAddress)[x];
              } else {
                ((uint8_t*)(void*)&tmpSector)[x] = ((uint8_t*)(void*)FLASH_FlashAddress)[x];
              }
            }
            FLASH_CurrentDataAddress = &tmpSector;
            FLASH_CurrentDataSize = IntFlashLdd1_ERASABLE_UNIT_SIZE;
            FLASH_RemainingDataSize = 0U;
          } else {
            FLASH_CurrentDataSize = (FLASH_RemainingDataSize / IntFlashLdd1_ERASABLE_UNIT_SIZE)*IntFlashLdd1_ERASABLE_UNIT_SIZE;
            FLASH_RemainingDataSize = FLASH_RemainingDataSize % IntFlashLdd1_ERASABLE_UNIT_SIZE;
            FLASH_NextSrcDataAddress = (FLASH_TDataAddress)((uint32_t)FLASH_NextSrcDataAddress + FLASH_CurrentDataSize);
          }
        } else {
          /* Remaining data size is multiple of sector size */
          FLASH_CurrentDataSize = FLASH_RemainingDataSize;
          FLASH_RemainingDataSize = 0U;
        }
        FLASH_CurrentCommand = FLASH_CMD_WRITE_ERASE;
        FLASH_CmdResult = (byte)IntFlashLdd1_Erase(IntFlashLdd1_DevDataPtr, FLASH_FlashAddress, FLASH_CurrentDataSize);
        if (FLASH_CmdResult != ERR_OK) { /* Erase command error? */
          FLASH_CmdPending = FALSE;    /* Command is finished */
        }
        return;
      } else {
        FLASH_CmdPending = FALSE;      /* Command is finished */
      }
      break;
    case FLASH_CMD_WRITE_ERASE:
      FLASH_CurrentCommand = FLASH_CMD_WRITE;
      FLASH_CmdResult = (byte)IntFlashLdd1_Write(IntFlashLdd1_DevDataPtr, FLASH_CurrentDataAddress, FLASH_FlashAddress, FLASH_CurrentDataSize); /* Write data */
      if (FLASH_CmdResult != ERR_OK) { /* Write command error? */
        FLASH_CmdPending = FALSE;      /* Command is finished */
      }
      return;
    default:
      FLASH_CmdPending = FALSE;        /* Command is finished */
      return;
  }
}

/*
** ===================================================================
**     Method      :  FLASH_OnError (component IntFLASH)
**
**     Description :
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void IntFlashLdd1_OnError(LDD_TUserData *UserDataPtr)
{
  LDD_FLASH_TErrorStatus FLASH_LDD_ErrorStatus;

  (void)UserDataPtr;                   /* Parameter is not used, suppress unused argument warning */
  FLASH_CmdPending = FALSE;
  FLASH_CurrentCommand = FLASH_CMD_NONE;
  IntFlashLdd1_GetError(IntFlashLdd1_DevDataPtr, &FLASH_LDD_ErrorStatus);
  if (FLASH_LDD_ErrorStatus.CurrentErrorFlags & LDD_FLASH_PROTECTION_VIOLATION) {
    FLASH_CmdResult = ERR_PROTECT;     /* Protection violation */
  } else {
    FLASH_CmdResult = ERR_VALUE;       /* Access error or Read collision error */
  }
}

/* END FLASH. */

#ifdef __cplusplus
}  /* extern "C" */
#endif

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
